### ISSUE TITLE
When clicking "Invite" an error is thrown after closing the alert dialog and no url is actually copied to the clipboard

### ISSUE THREAD

**Issue by Nezteb** [StephenTurley/wordual#1]
`Uncaught (in promise) DOMException: Document is not focused.`

Chrome 100.0.4896.75
macOS 12.3.1

**Comment by StephenTurley** [comment]
Thanks for reporting. I'll take a look at it. Seems isolated to chrome on Mac. Could try another browser as a work around.

**Comment by Nezteb** [comment]
Fixed! https://github.com/StephenTurley/wordual/pull/2

**Comment by StephenTurley** [comment]
fix has been deployed. 
Thanks again!
